spring.application.name=MyProjectBackend
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
usda.api.key=ZPMbiNDja02D6CgagMSb2EFixd0OgQt5qucr2yBe
