spring.application.name=MyProjectBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_tracker
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

usda.api.key=ZPMbiNDja02D6CgagMSb2EFixd0OgQt5qucr2yBe
